### ISSUE TITLE
Incorrect Parent Folder Name When Moving Folders

### ISSUE THREAD

**Issue by FadeDreams** [nvim-telescope/telescope-file-browser.nvim#357] opened 2024-01-28 09:45 UTC
### Description

I have encountered a potential issue when using the telescope-file-browser.nvim plugin. When I mark a folder for moving, navigate to another folder, and then press Alt + m to move the marked folder, the moved folder's name becomes the parent of the desired folder instead of retaining its original name.

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794
```

### Operating system and version

Debian12

### Steps to reproduce

    Open the telescope-file-browser.nvim file browser.
    Mark a folder for moving (e.g., using Tab).
    Navigate to another folder.
    Press Alt + m(insert mode) or m (normal mode) to move the marked folder.

### Expected behavior

I expect the marked folder to be moved to the current location, the moved folder should be keep its original name.

### Actual behavior

The moved folder's name becomes the parent of the desired folder.

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope-file-browser.nvim",
    dependencies = {
      "nvim-telescope/telescope.nvim",
      "nvim-lua/plenary.nvim",
    },
    config = function()
      require("telescope").setup({})
      require("telescope").load_extension("file_browser")
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment] 2024-01-29 17:57
I believe this was fixed not too long ago.
https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/344

Can you update telescope-file-browser and see if the issue still persists?

**Comment by FadeDreams** [comment] 2024-01-29 18:51
Hi @jamestrew,

Thanks for investigating the issue. I wanted to let you know that I've updated the telescope-file-browser plugin, and you can verify the changes in the Git log below: `~/.local/share/nvim/lazy/telescope-file-browser.nvim$ git log --oneline --graph
* 6dd6522 (HEAD -> master, origin/master, origin/HEAD) fix(git): show status for git submodules (#356)
* 6f735a6 chore: format minimal config (#355)
* ee7e5aa chore: update bug report minimal config to use lazy (#354)
* 4bd5657 fix(action): prevent collapse_dirs from trying to open file (#351)
*** 8e05433 fix(action.move): moving folders (#344)**
* afb612a Revert "fix(action.move): moving folders (#342)" (#343)
`  However, I regret to inform you that the issue is not yet resolved on my end. If you have any insights or suggestions, I would greatly appreciate your assistance.
I use lazyvim, and this is my configuration for telescope-file-browser: `return {
  "nvim-telescope/telescope-file-browser.nvim",
  dependencies = {
    "nvim-telescope/telescope.nvim",
    "nvim-lua/plenary.nvim",
  },
  keys = {
    {
      "<leader>v",
      ":Telescope file_browser path=%:p:h select_buffer=true<CR>",
      desc = "Browse Files",
    },
  },
  config = function()
    require("telescope").load_extension("file_browser")

    -- Apply the settings to Telescope
    require("telescope").setup({
      results_prompt = true,
      extensions = {
        file_browser = {
          hidden = true,     -- Show hidden files
          no_ignore = false, --false: see gitignore files, true to ignore them
          grouped = true,    -- Group directories first
        },
      },
      defaults = {
        path_display = { "absolute" }, -- Use absolute paths in the file browser
        previewer = true,
        initial_mode = "insert",
        --layout_config = { height = 40 }
      },
    })
  end,
}
`

**Comment by jamestrew** [comment] 2024-01-30 01:08
Can you provide more details on how to reproduce this.
I've tried precisely this
> Open the telescope-file-browser.nvim file browser.
Mark a folder for moving (e.g., using Tab).
Navigate to another folder.
Press Alt + m(insert mode) or m (normal mode) to move the marked folder.

with the minimal config and I'm not getting any strange behaviors.

https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/66286082/e964ab0f-1b4d-4436-a8a8-4f8dd52be727

**Comment by FadeDreams** [comment] 2024-01-30 07:41
I hope this message finds you well. I wanted to update you on the situation regarding the issue we discussed. I attempted to resolve it by cleaning up my Neovim configurations using the following steps:
 ```
rm -rf ~/.config/nvim ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim
 ```
Afterwards, I created a new ~/.config/nvim/init.lua from [here](https://github.com/folke/lazy.nvim) file with the following content: 
```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
```
and another ~/.config/nvim/min.lua 
```
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope-file-browser.nvim",
    dependencies = {
      "nvim-telescope/telescope.nvim",
      "nvim-lua/plenary.nvim",
    },
    config = function()
      require("telescope").setup({})
      require("telescope").load_extension("file_browser")
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```
I then tested the setup using: 
```
~/.config/nvim$ nvim -u min.lua
```


https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/16093179/4bef844a-766c-4570-a4a9-200fec33f81d



However, it did not work as expected. If you have any insights or suggestions on how to resolve this, I would greatly appreciate your assistance.

Thank you for your time and help.

**Comment by jamestrew** [comment] 2024-01-31 01:40
I'm sorry. I tried to follow exactly your steps, even downgraded to neovim v0.9.4 but I'm still not able to replicate this issue.
Without the ability to replicate this, I'm not able to debug what is causing this issue for you.

**Comment by FadeDreams** [comment] 2024-01-31 12:36
Thank you for your continued efforts in trying to help me resolve this issue. I've done some tracking down on my end, and it seems that the problem might be related to the line:
`local new_path_absolute = new_path:absolute()
`
which is part of the fb_actions.move function in the file "lua/telescope/_extensions/file_browser/actions.lua" . This line is giving unexpected results for me. For example, when I attempt to move "folder1" into "folder2," the result is something like "parent_of_folder1/folder2/parent_of_folder1," which is not the expected behavior. I hope this information helps in identifying the root cause of the issue.

**Comment by jamestrew** [comment] 2024-02-01 02:28
Interesting.
If you can, can you put
```lua
      vim.print {
        selection = old_path_absolute,
        basename = basename,
        target_dir = target_dir,
        new_path = new_path_absolute,
      }
```
below that line 
> `local new_path_absolute = new_path:absolute()`

then repeat the reproduction steps and share the results?

I don't think it's the `new_path:absolute()` that's the issue but something before that.

**Comment by FadeDreams** [comment] 2024-02-01 07:29
Thanks for your suggestion. I've added the debug print statements below the line:
```
{
  basename = "parent_of_folder1",
 new_path = "/home/m/parent_of_folder1/folder2/parent_of_folder1",
 selection = "/home/m/parent_of_folder1",
 target_dir = "/home/m/parent_of_folder1/folder2"
}

```
```
before :‌
 m@debian:  ~/parent_of_folder1$ tree

├──   folder1
└──   folder2
moving folder1 into folder2
after:
m@debian:~/parent_of_folder1$ tree
.
└── folder2
      └── parent_of_folder1


```
    ...
    if new_path:exists() then
      table.insert(skipped, basename)
    else
      local new_path_absolute = new_path:absolute()

      vim.print {
        selection = old_path_absolute,
        basename = basename,
        target_dir = target_dir,
        new_path = new_path_absolute,
      }
      selection:rename {
        new_name = new_path_absolute,
      }
    ...
```

**Comment by jamestrew** [comment] 2024-02-03 02:53
Wow. I'm thoroughly confused.
Does using `<tab>` to select and delete directories work as expected?
If it does and you're willing, can you try adding a couple of print statements a few lines higher?
```lua
  local target_dir = get_target_dir(finder)
  local moved = {}
  local skipped = {}

  for idx, selection in ipairs(selections) do
    local old_path_absolute = selection:absolute()
    print(old_path_absolute)
    if vim.fn.isdirectory(old_path_absolute) == 1 then
      old_path_absolute = vim.fs.dirname(old_path_absolute)
    end
    local basename = vim.fs.basename(old_path_absolute)
    print(basename, old_path_absolute)
```

And just to double check, nothing but the print statements should be different here.

**Comment by FadeDreams** [comment] 2024-02-03 05:26
I've confirmed that using <tab> to select, delete, and copy directories works as expected. However, I've also tested this in WSL Ubuntu on Windows 10, and I'm encountering the same unexpected results when moving directories.
```
/home/m/parent_of_folder1/folder1
nil /home/m/parent_of_folder1
[file_browser.actions.move] Moved: parent_of_folder1
```

```
before :‌
 m@debian:  ~/parent_of_folder1$ tree

├──   folder1
└──   folder2
moving folder1 into folder2
after:
m@debian:~/parent_of_folder1$ tree
.
└── folder2
      └── parent_of_folder1
```

```
  for idx, selection in ipairs(selections) do
    local old_path_absolute = selection:absolute()
    print(old_path_absolute)
    if vim.fn.isdirectory(old_path_absolute) == 1 then
      old_path_absolute = vim.fs.dirname(old_path_absolute)
    end
    print(basename, old_path_absolute)
    local basename = vim.fs.basename(old_path_absolute)
    local new_path = Path:new { target_dir, basename }
    if new_path:exists() then
      table.insert(skipped, basename)
```

**Comment by jamestrew** [comment] 2024-02-03 19:19
Ohhh I see what the issue is and why I couldn't reproduce it.
You're not using `fd`, am I correct? I'm able to reproduce this when I disable the use of `fd`.

I'll work on a fix for this. Thanks for helping me debug this.

**Comment by jamestrew** [comment] 2024-02-04 03:51
@FadeDreams If you can try out the linked PR, that would be great.

**Comment by FadeDreams** [comment] 2024-02-04 06:10
You're correct; I haven't installed fd. However, I tested the linked PR 358, and it worked for me in the situation even without installing fd. Thanks for your quick response and efforts to fix the issue!

**Closed** 2024-02-09 05:29 UTC
Labels: bug
