### ISSUE TITLE
Telescope-file-browser not showing files on Windows WSL

### ISSUE THREAD

**Issue by BozeBro** [nvim-telescope/telescope-file-browser.nvim#239] opened 2023-02-19 04:29 UTC
### Description

When looking for files in my terminal, the files do not show, I cannot click on them or open them in a buffer.
I can see the files on my mac running neovim 0.8. telescope works as normal in my wsl2 though.

### Neovim version

```markdown
NVIM v0.9.0-dev-672+g4876654d4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_UNIBI_HAS_VAR_FROM -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -I/home/benny101/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/benny101/neovim/.deps/usr/include -I/home/benny101/neovim/build/src/nvim/auto -I/home/benny101/neovim/build/include -I/home/benny101/neovim/build/cmake.config -I/home/benny101/neovim/src
Compiled by benny101@Ben

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

### Operating system and version

Ubuntu 20.04.5 LTS on Windows 10 x86_64

### Steps to reproduce

Have fzf installed.
Copy the code into a test config file.lua

I have a color scheme to make things clearer to see. I have some default keymaps to simply test out the commands. 

### Expected behavior

I should be able to click on files, toggle, all that fun stuff that the plugin offers.

### Actual behavior

files are not seen and cannot be clicked or toggled
![Screenshot_20230218_095755](https://user-images.githubusercontent.com/62128128/219922265-3b6cee9c-ea94-44d2-9f7d-516b460114e4.png)
Actual files in directory
![Screenshot_20230218_095852](https://user-images.githubusercontent.com/62128128/219922269-cd7e7a83-8f6d-4854-8cb5-02b4a45d7e7c.png)

### Minimal config

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)
local tele = {
    {"folke/tokyonight.nvim"},
	{ "nvim-lua/plenary.nvim"},
	{
		"nvim-telescope/telescope.nvim",
		dependencies = {
			{ "https://github.com/nvim-telescope/telescope-fzf-native.nvim.git", build = "make", name = "fzf" },
			{ "nvim-telescope/telescope-file-browser.nvim", name = "file_browser" },
			{ "nvim-lua/plenary.nvim" },
		},

		config = function(_, opts)
			local tele = require("telescope")
			tele.setup(opts)
			tele.load_extension("fzf")
			tele.load_extension("file_browser")
		end,
	},
}
require("lazy").setup(tele)
```

**Comment by jamestrew** [comment] 2023-02-19 04:58
Thanks for the min config, helps a lot with figuring things out.
That said, using your min config, I can't reproduce the issue you're having. Nothing in your config screams out to me as wrong either.

Is `fd` functioning correctly for you? Can you try with `:Telescope file_browser use_fd=false` and see if you get the same thing?

**Comment by BozeBro** [comment] 2023-02-19 06:58
It has to be the fd. When I turn it off, The Telescope file_browser works how I expect it too. I'm thinking this is due to how to install fd on Ubuntu https://github.com/sharkdp/fd#installation where
We download the binary fdfind and then simlink it.

**Comment by jamestrew** [comment] 2023-02-19 19:14
Sounds good. I'll close this issue unless you continue to have issues.

**Closed by jamestrew** 2023-02-19 19:14 UTC
Labels: bug

**Comment by dantearaujo1** [comment] 2023-02-25 01:47
Im having the same issue and using use_fd=false solves the problem
