### ISSUE TITLE
how to set browse path to the current buffer instead of cwd

### ISSUE THREAD

**Issue by rzksobhy78** [nvim-telescope/telescope-file-browser.nvim#21] opened 2021-12-11 02:57 UTC
I'm trying to set browse path to the current buffer path
I used
`file_browser = { path = require('telescope.utils').buffer_dir() }`
didn't however when I used something like
`file_browser = { path = "~/dev" }`
it worked and it doesn't give an error like buffer_dir() is not a string

**Comment by fdschmidt93** [comment] 2021-12-11 05:42
`file_browser = { path = "%:p:h" }` should now hopefully work as intended as I just now cleaned up the separation a bit better.

See https://github.com/nvim-telescope/telescope.nvim/issues/1440 on a discussion why `buffer_dir` is not necessary and cannot be used here. You are evaluating a function to early and it essentially gives you the cwd when you start nvim.

Closing for now unless there's more.

**Closed by fdschmidt93** 2021-12-11 05:42 UTC

**Comment by rzksobhy78** [comment] 2021-12-11 09:17
that didn't solve my problem
and `:lua print( require('telescope.utils').buffer_dir() )` actully gives me my buffer path
and `file_browser = { path = "%:p:h" }` it tries to open a directory named %:p:h in my root
I tried to use `file_browser = { path = "vim.fn.expand('%:p:h') } }" }` didn't work either
and also I tried `require("telescope").extensions.file_browser.file_browser({ cwd = vim.fn.expand("%:p:h"), })`

by the I forgot to thank you for the great plugin I love it

**Comment by fdschmidt93** [comment] 2021-12-11 14:42
What is it you are actually trying to do? Set the value at setup or at an individual call? Please give a full description. I'm sorry, but I will close future "question" feature requests with incomplete descriptions. The time I can spend at the moment on open source is rather brief and I prefer not to go on a goose chase, especially after I elaborated beforehand on reddit that you should put in more effort into your questions.

> and :lua print( require('telescope.utils').buffer_dir() ) actully gives me my buffer path

Have you read the issue I was referring to? From what you are writing, you are passing that at extension set up. That cannot work.

> file_browser = { path = "%:p:h" }

Works for me when you do it at setup. Did you update the repo to latest master?

Please fill out an issue **with all details** and a full repro after having updated to latest telescope, telescope-file-browser, and either neovim 0.6 or neovim master.
