### ISSUE TITLE
How to override default mappings

### ISSUE THREAD

**Issue by j-hui** [nvim-telescope/telescope-file-browser.nvim#5] opened 2021-11-19 04:48 UTC
I'm trying to override the default mappings given by this extension. For example, I want to remape `<C-f>` to `<Right>`. However, I am unable to do so.

This is an extract from my config (I have a lot of other mappings):

```vim
    local fb_actions = require 'telescope'.extensions.file_browser.actions
    local imaps = {
      ['<C-f>'] = { '<Right>',  type = 'command' },
    }
    require'telescope'.setup {
      extensions = {
        file_browser = { mappings = { i = imaps, }, },
      },
    }
```

I was looking through the source code for this plugin, and saw that the fb_actions were being mapped in [`attach_mappings`](https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/master/lua/telescope/_extensions/file_browser/picker.lua#L92). This runs after extension `mappings` are set, meaning my mappings are being overriden by this plugin.

I'm still new to Telescope and the way things are organized, so apologies if this is already answered elsewhere, but how can I override `attach_mappings` this to disable these mappings? And is there any way I can do this without having to copy and paste in the `replace_if` chunk of code? (I'm not actually sure what that's doing.)

**Comment by fdschmidt93** [comment] 2021-11-19 07:18
Thanks for the issue!

Your `setup` should work, but in trying to debug this I've realized some oddities.

Are you using something like https://github.com/tjdevries/astronauta.nvim to do keymappings in lua and pass an actual lua function? What may happen (depending on your startup config), that the file browser is mapped before the extension is set up and therefore it gets mapped without config.

I've had that issue and now map it via a viml command and then overriding keymaps as intended. 

Furthermore, it looks like unmapping does not seem to work though?

`["<C-f>"] = false` should unmap `<C-f>`. 

I'll look into this more.

**Comment by fdschmidt93** [comment] 2021-11-19 09:50
I think being unable to unmap mappings that are attached by default like so

https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/a9d361cac3194ba66e76ddf96ee9b2c7e7ab9a73/lua/telescope/_extensions/file_browser/picker.lua#L79-L111

is an upstream bug. 

Could you please confirm that the below holds for you? Specifically, mapping `<C-a>` to `false` doesn't achieve anything while mapping it to the `print` function overrides the mapping as intended?

```lua
require "telescope".setup {
  pickers = {
    git_branches = {
      mappings = {
        i = {
          ["<C-a>"] = false, -- should unmap create branch, does not
          ["<C-a>"] = function() print("test") end, -- successfully overrides
        },
      },
    },
  },
}
```

**Comment by j-hui** [comment] 2021-11-19 20:35
@fdschmidt93 thanks for the fast response!

> Could you please confirm that the below holds for you? Specifically, mapping <C-a> to false doesn't achieve anything while mapping it to the print function overrides the mapping as intended?

Yeah, I can replicate that behavior with any of the built-in pickers. For unneeded mappings, I figured one could always map to `function() end` to make it a nop, effectively unmapping it.

> Are you using something like https://github.com/tjdevries/astronauta.nvim to do keymappings in lua and pass an actual lua function? What may happen (depending on your startup config), that the file browser is mapped before the extension is set up and therefore it gets mapped without config.

I'm not totally sure what this means. I'm not using astronauta; my mappings are defined all over the place. My vimrc setup is a bit of an over-engineered mess with callbacks out the wazoo, but all the telescope-specific mappings are being set using the `mappings` mechanism that it provides. (Though I'm not really sure if that's the right thing to do.)

**Comment by fdschmidt93** [comment] 2021-12-27 16:58
I would now close this as the relevant (upstream) PRs have merged. Please let me know in case there's more to do here.

**Closed by fdschmidt93** 2021-12-27 16:58 UTC
