### ISSUE TITLE
Switch from file/folder mode changes current directory back to 'cwd'

### ISSUE THREAD

**Issue by miguelmoraperea** [nvim-telescope/telescope-file-browser.nvim#43] opened 2021-12-31 20:39 UTC
### Description

Switch from file/folder mode changes current directory back to `cwd`, that seems a bit weird, I would expect the current directory to remain the same. Ultimately, as a user, I only want to change the mode from where I am, I don't want to go back to `cwd` unless I specifically ask for it.

### Neovim version

```markdown
NVIM v0.7.0-dev+792-gc46f7caad
Build type: RelWithDebInfo
```

### Operating system and version

Ubuntu 20.04

### Steps to reproduce

1. Open file browser in file mode
2. Navigate to a sub-directory
3. Change to folder mode
4. The current directory goes back to `cwd`

### Expected behavior

1. Open file browser in file mode
2. Navigate to a sub-directory
3. Change to folder mode
4. The current directory remains the same, only change the mode to folder mode.

### Actual behavior

![change-to-folder-mode-goes-back-to-cwd](https://user-images.githubusercontent.com/42681212/147838434-2481dc12-833d-416d-82c7-3fd2cb158496.gif)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment] 2022-01-01 10:41
> This behavior is very much intentional, since folder browsing from cwd to low-level folders by means of fuzzy finding is in most scenarios always fast and enables file operations swiftly across many layers of directories (also upwards from finder.path), which is a key feature of this extension. On the contrary, this change would make such workflows a lot more complicated (cf. gif on README, <C-W> I suppose now every time in between?) while seemingly offering hardly any practical gain. Or am I missing something?

> What I agree though is that there should be a user-friendly mechanism to set finder.cwd, very much in line with #40 and/or enabling this behavior optionally.

Copying my thoughts from the linked PR here for reference, as I can imagine users seek one of the two behaviors.

**Comment by miguelmoraperea** [comment] 2022-01-01 22:26
Regarding your comment about copying files upwards of path:

You can still copy files/folders upwards because `cwd` did not change, only the path from where the finder starts has changed.


Regarding the practical gain:

The main benefit I see is this, is that, consider you are working in a `repoA` `/home/you/Desktop/repoA`

And you are exploring files/folders using the telescope-file-browser, so you decide to go checkout what files you have in a directory upwards of 'cwd' outside 'repoA' for example in `/home/you`, you probably have lots of folders and lots of files, but you are only interested in seeing the folders... perhaps you are looking for another repo to work in, so you change to folder-browse mode, but you can't, because now you are back in cwd of `repoA`. (that's annoying.... mmm).

Try doing that, with the current implementation you won't be able to do it. Then try it with my PR, you will see that once you navigate back to any directory, you can switch to folder mode in-place, without jumping back to cwd, and start searching.

Check the following demo, I'm going 1 directory upward from `cwd` and switching to folder mode, but I can't, unless I switch to use the changes in the PR:

![file_and_folder_mode_demo](https://user-images.githubusercontent.com/42681212/147861368-b103aac3-3743-433a-90a2-816c0a732781.gif)

**Comment by fdschmidt93** [comment] 2022-01-02 09:03
`telescope-file-browser` is not meant to replace any file browser (or project browser for that matter), but be launched from project root (neovim's cwd), rather than `$HOME`. CLI `fzf` or [telescope-project](https://github.com/nvim-telescope/telescope-project.nvim) are much better projects for that.

> You can still copy files/folders upwards because cwd did not change, only the path from where the finder starts has changed.

But `folder_browser` now starts every time from the `finder.path`. Whenever I move or copy files, accessing folders from different branches is a lot more cumbersome now.

> Check the following demo, I'm going 1 directory upward from cwd and switching to folder mode, but I can't, unless I switch to use the changes in the PR:

That should be a use case supported by setting neovim's `cwd` anew.

> Try doing that, with the current implementation you won't be able to do it. Then try it with my PR, you will see that once you navigate back to any directory, you can switch to folder mode in-place, without jumping back to cwd, and start searching.

Again, I'm OK having this opt-in if there is a good PR with maybe making your PR an optional setting. But this won't become the default, since it inherently changes the envisaged workflow of `telescope-file-browser` opened from project root.

**Comment by miguelmoraperea** [comment] 2022-01-03 02:43
> telescope-file-browser is not meant to replace any file browser (or project browser for that matter), but be launched from project root (neovim's cwd), rather than $HOME

I haven't change that behaviour, when you launch the file browser, it still launches it from `cwd`.

Have you got a chance to try this PR yet?

>  CLI fzf or telescope-project are much better suited for swiftly switching between projects.

`telescope-file-browser` has everything that I need to change a project (folder-browse and set-cwd) but the problem is that it only works well if you are in `cwd` I cannot change to folder-mode seemlesly outside `cwd`, which is a bummer in my opinion. And I think we could improve it, if we do that, we'll get (or maybe not lose) a lot of users.

>  Whenever I move or copy files, accessing folders from different branches (of the folder tree) is a lot more cumbersome now.

I think this is an implementation issue, that we need to address, perhaps we should create tickets for this, I'm not familiar yet with the troubles you are mentioning, perhaps will need some clarification, what exactly is the issue?

I also feel that not being able to fully navigate, upwards of cwd, or to copy files from/to outside of my project will be a deal-breaker for a lot of users (including me).

Having to change `cwd` just to make this work upwards of `cwd` is an extra step that shouldn't be necessary. Changing `cwd` can have repercussions on other plugins and as a user I rather not have to do that, twice actually, because I need to do that first to set `cwd`, then do my copy operations, then set `cwd` again back to my original location. It doesn't make much sense to me, but maybe I'm missing something and you could clarify why is it that you want the user to have to change the `cwd` before and after any operations outside `cwd`.

If we don't want the user to do that, but we can't at the moment because of the existing code base, then perhaps we should discuss on how to refactor the codebase. I'm willing to help, but I need to understand what are the goals/vision of the project, and see if that aligns to what I have in mind.

In my mind, `cwd` is just the starting point from where the file-browser opens.

After that, the user should be able to explore downwards/upwards with the same functionality, and copy/paste/create files anywhere on the file-system, like a true file browser.

If in your mind/vision, you only want to create/copy files downwards of `cwd`, then we should specify that on the README more clearly.

At the moment it only says:
> Copy (multi-selected) files or folders to cwd

When I first read this, I suspected that was the `current` behavior, and that they were plans to improve it.

And I get the feeling is the same case for using the file-explorer features upwards of `cwd`. I thought there was a plan/intention to improve it to work upwards of `cwd`, but from what you are saying, that is not the intended behavior.

If you really don't want to support anything upwards of `cwd`, then we should make that clear for the users in the README.

Something like this:

>  The telescope-file-browser file operations and browsing, are only meant to work for any file/directories under `cwd`. This means that to navigate/copy/create/delet files outside of `cwd` you need to first change the `cwd`. This is the intentional behaviour because _[enter reason here]_

I personally see a big potential for this plugin, but I can also see that it needs lots of work yet.

It can be very useful for my personal workflow, so I'd be happy to help, but first I need to verify that my vision/aligns with where this project is going.

I'm happy to chat/connect with you to share what I have in mind, and to hear what are your plans for this plugin. :)

**Comment by fdschmidt93** [comment] 2022-01-03 08:30
I'll update my reply throughout the day and remove this disclaimer once I'm finished. I'd appreciate it if thoughts were more compressed; it's a lot to digest and work to fully follow. 

> Have you got a chance to try this PR yet?

Yes, it behaves as expected and struggles with issues I've mentioned repeatedly. See below for a depth walk-through.

> I'm not familiar yet with the troubles you are mentioning, perhaps will need some clarification, what exactly is the issue?

As mentioned before, please reproduce the GIF of the README with your workflow. Copying files from multiple folders to some random target folder in your project (here `telescope-file-browser.nvim`)

1. Start from `$HOME`
2. Use folder browser to go to `telescope-file-browser.nvim` (which now is `path`, `cwd` is still home)
3. Re-trigger folder browser from file browser to launch folder browser properly in `path`
4. Go to lower folders from which I want to copy within `telescope-file-browser.nvim`
5. How do I go up? `cwd` is `$HOME`

> I also feel that not being able to fully navigate, upwards of cwd, or to copy files from/to outside of my project will be a deal-breaker for a lot of users (including me).

I've meant that with your PR was merged as is this would be a lot more cumbersome right now. Moving horizontally or upwards of `path` is very straightforward if the folder browser is anchored to `cwd`. Again, this envisages the workflow that neovim `cwd` is set to project root.

**Comment by fdschmidt93** [comment] 2022-01-03 22:06
A mixture of solutions come to mind here:
* Ppt-in for tying `finder.cwd` to `finder.path`
* Upwards movement via separate `finder` action that launches a finder that as results only has upwards folders from `path`

These then will be able to be combined with something like #40 that sets the `finder.cwd` and/or `nvim` `cwd` without refreshing the picker.

**Comment by miguelmoraperea** [comment] 2022-01-03 22:51
You keep saying my PR makes copy files more 'complicated' and 'cumbersome', but you don't provide any other details, is hard for us to address the issue when you don't communicate clearly what is the issue.

This is why my replies are getting longer, I'm not looking to waste your time, and I'm sure you don't want to waste our time either, you mentioned multiple times that your time to open-source is limited, we'll, you are not the only one, we all have limited time dedicated to open-source.

From my side, I'm trying to be efficient with my replies, I know you are in Germany, so we can only communicate once per day, I'm trying to understand what do you mean by the 'complicated' and 'cumbersome', It hasn't been clear to me if you were talking about the code implementation, extensibility, or the user workflow.

Let's focus on your feedback... you said:

`   1. Start from $HOME
    2. Use folder browser to go to telescope-file-browser.nvim (which now is path, cwd is still home)
    3. Re-trigger folder browser from file browser to launch folder browser properly in path
    4. Go to lower folders from which I want to copy within telescope-file-browser.nvim
    5. How do I go up to telescope-file-browser.nvim? cwd is $HOME and path is some random folder.
`

That is right, 'cwd' is `HOME`, I don't see what is the issue here, you started from `HOME` and you never changed the `cwd`.

You go up to `telescope-file-browser` by either of these options:

1. <C-W> (to go back to HOME) then search for telescope-file-browser.
2. Navigate up each level by using `../`

If you want to do everything from telescope-file-browser, then you do the following:

1. Start from $HOME
2. Use folder browser to select telescope-file-browser.nvim and press <C-W> now telescope-file-browser.nvim is `cwd`, then you do copy/paste using your usual workflow, the same as the README.

Like I said, I don't see what is wrong here, could you please clarify what is the issue? How does this makes the workflow more complicated/cumbersome? Please provide a gif if needed.

**Comment by fdschmidt93** [comment] 2022-01-03 23:02
> You go up to telescope-file-browser by either of these options:
(to go back to HOME) then search for telescope-file-browser.
Navigate up each level by using ../

As mentioned, I don't want to do either of these things? (1) Can be slow if you have many folders and (2) requires a lot of steps.

> Use folder browser to select telescope-file-browser.nvim and press <C-W>, now telescope-file-browser.nvim is cwd, then you do copy/paste using your usual workflow, the same as the README.

What do you mean? `cwd` is `HOME` so you'd go back to home as that what's `<C-W>` bound to?  Moreover, your PR changes `folder_browser` to use `finder.path`. How would that help?

I'm still at odds, why do we discuss this when I'm OK making your behavior opt-in?

**Comment by miguelmoraperea** [comment] 2022-01-03 23:05
So what is the issue that you don't like about this PR? I still don't get it....

**Comment by miguelmoraperea** [comment] 2022-01-03 23:06
My PR doesn't change `cwd`, so that has no effect on the functionality of the plugin from the project root.

**Comment by fdschmidt93** [comment] 2022-01-03 23:07
What does `cwd` matter if the folder browser uses `finder.path`??

**Comment by miguelmoraperea** [comment] 2022-01-03 23:11
Are you considering the change in PR #40?
https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/40

I get the feeling you are not considering the change `cwd` functionality.

**Comment by fdschmidt93** [comment] 2022-01-03 23:14
I don't want to have to trigger #40 every time now I'm moving across folders, which I now have to because folder browser always starts from `finder.path`. How is that not clear?!

**Comment by fdschmidt93** [comment] 2022-01-03 23:16
Again, I'm ok with making your behavior opt-in, I'm really confused why this is not an acceptable compromise. I even started coding up an upwards folder finder as means to further address this.

**Comment by miguelmoraperea** [comment] 2022-01-03 23:16
You don't do that... you only trigger it once, the workflow is as follows:

1. Open nvim from `HOME`  or wherever, is not important.
2. Open file-browser
3. Switch to folder-browser
4. Find the project folder
5. Press <C-t> to change `cwd` to the project root
6. Continue doing your copy/files as needed... you can come back to project root whenever you want by pressing <C-W>

**Comment by miguelmoraperea** [comment] 2022-01-03 23:17
I'm trying to understand what is the default behavior that you want... that is all... because I don't see the difference yet.

**Comment by miguelmoraperea** [comment] 2022-01-03 23:18
Do you agree with the above workflow?

**Comment by fdschmidt93** [comment] 2022-01-03 23:20
Between 6 and 7, if you move to an extra folder you have to reanchor to root again by `<C-w>`. I essentially now have to press `<C-w>` every time if I want to launch folder browser from project root with your PR as is.

**Comment by miguelmoraperea** [comment] 2022-01-03 23:25
That is correct, but I think that is fine, If you want to launch folder-mode from `cwd` a user can create a custom mapping for that.

Or be ok with the 2 step process, press `<C-W` then open folder-browse mode.

That is OK.

My change however fixes a big problem that we cannot go around with the current default behaviour:

1. Start nvim from HOME or whatever
2. Go upwards of `cwd` let's say to `/`
3. Switch to folder-browse mode (we currently can't, it jumps back to HOME).

Instead my PR allows you to do this: 

1. Start nvim from HOME or whatever
2. Go upwards of `cwd` let's say to `/`
3. Switch to folder-browse mode now you are in folder mode in `/`
4. Search for another repo
5. Change `cwd` to that repo using `<C-T` 
6. Now I can start working in my new repo!!!!

I can't do that with the current implementation.

**Comment by miguelmoraperea** [comment] 2022-01-03 23:30
Essentially, yes my change my messed up with the way you are used to opening folder mode. But it addresses a larger issue, which is switching to folder-mode in any directory upwards of `cwd`.

There are multiple options to get a user to open folder-mode from `cwd`, I propose creating a new mapping for that.

That way the user can press `<C-X` (X is an example) to open folder-browse mode directly from `cwd` or do the 2 step process. `<C-W` to go back to `cwd` the toggle folder-mode.

But the toggle folder-mode should always open from path, and not from `cwd`, does that makes sense?

**Comment by fdschmidt93** [comment] 2022-01-03 23:36
> That is correct, but I think that is fine, If you want to launch folder-mode from cwd a user can create a custom mapping for that.

But contrary to your workflow, it does not suit mine and I prefer the current workflow.

I'm confused, you similarly could just as easily can wrap `fb_actions.toggle_browser`.

> But it addresses a larger issue, which is switching to folder-mode in any directory upwards of cwd

How does your PR as is help going upwards? You typically now can more easily launch folder browser mode from downwards folders. Otherwise users would always have to launch `nvim` from `$HOME`. It's also not that important. #46 will also help.

Again, why is it so much a problem making this an option rather than default behavior? Much of the file browser probably needs user-specific configuring anyways. One of the prototypical uses of `nvim` is launching it from project root, where the current way of things in my opinion is just more convenient. I'd be happy to have to opt-in into the current way of things in favor of yours if we'd have larger feedback, but that's not so easy to acquire. Otherwise, we are defaulting to the current way of things as it literally pretty much constitutes a breaking change in workflow.

I've mentioned repeatedly that setting `finder.cwd` better is something we'll have to address and I'm happy to make your behavior opt-in.

Setting `finder.cwd` is something I've also started addressing here https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/46

Making your behavior opt-in -- again, a good PR welcome.

**Comment by miguelmoraperea** [comment] 2022-01-03 23:53
I think we have different views on how the file/folder browser should operate.

I get the feeling you want to open file-browser and the switch to folder move, and then have 2 different operations, either search downwards, or search upwards.... is that correct? (based on your upwards search PR)

In my opinion, moving upwards is not an issue, we already have a PR that will add a `go-to-HOME` command. If you need to move further up, you could use `../` twice then you are at the root. (I hardly think users will need to search anything from root.). Essentially moving up is very easy right now, the only issue is switching to folder-mode once you are up, which is what my PR addresses.

So the workflow is like this:

`<C-S>` to go to HOME (from PR# 40), then switch to folder-mode (thanks to my PR), then do a downwards search as usual. Once you have found your target repo, `<C-T>` (from PR# 40)> to change the `cwd`, and you are good to go!!!

I think this workflow is a lot easier. And is mostly already implemented, no need to add an upwards search.

Think about it. Keep it simple. ;)

Good night!

**Comment by miguelmoraperea** [comment] 2022-01-04 01:08
Another thing to consider with the upwards-search approach is that any folder that branches of the current `cwd` won't be found by either the upwards or downwards search.

For example if `cwd` is `/home/you/Desktop/repoA` you won't be able to find `/home/you/Desktop/dir1/repoB`

Because `repoB` is neither downwards or upwards of `repoA`.

That is why I think the downwards-only approach is better.

**Comment by fdschmidt93** [comment] 2022-01-04 09:39
`telescope-file-browser.nvim` is primarily intended to replace `nerdtree`, `nvim-tree`, etc. (project-oriented browsers or, hereafter, "browsers") rather than `ranger`, `vifm`, or similar (hereafter "explorers"). For browsers as is makes perfect sense, for explorers probably yours is preferred.

> So the workflow is like this:

We are primarily discussing multi-hop scenarios. You seem to be missing my point, that on follow-up hops, you will always (1) have to return to `cwd` and (2) only then can trigger folder browsing. This hampers copying/moving across multiple folders in context of "browsing".

Further, again, same outcome of your workflow is achieved with a simple action that sets `finder.cwd` prior to step 2 so I don't find that your PR doesn't adds major convenience here, you'd just have to reanchor before step 2 - as per your words, that's super easy. Plus, both actions will be combine-able into one (you can then literally add `fb_actions.goto_home + fb_actions.set_cwd` to form a new action).

The key point of your PR is "exploring". Another way of looking at is it is primarily about shifting when you have to set `finder.cwd` anew from where to trigger the folder browser.

Moving upwards we can also discuss to death. Some people like `HOME`, others follow `..` and some may appreciate the upwards finder. And then there's people for which a discussion on up-/downwards movement is irrelevant as they pretty much always open `nvim` from project root and switch folders anchored to that. Though, again, with your PR, I'd now have to re-anchor to project root every time with `<C-w>` if I want to browse folders from `cwd` in multi-hop scenario.

> That is why I think the downwards-only search approach is better.

That's totally fine and I'm very happy to enable that. I'm happy to opt into "exploring", have a dedicated segment on the README addressing our discussion, but first and foremost, `telescope-file-browser.nvim` for me is an explorer to be launched from project root.

I'll take myself a final pass at putting this to practice tomorrow evening, but for the time being please accept in terms of "browsing", I very much prefer as is.

**Comment by miguelmoraperea** [comment] 2022-01-04 17:39
> telescope-file-browser.nvim is primarily intended to replace nerdtree, nvim-tree, etc. (project-oriented browsers or, hereafter, "browsers") rather than ranger, vifm, or similar (hereafter "explorers"). For browsers as is makes perfect sense, for explorers probably yours is preferred.

Ok, now you are introducing 2 new terms: `browser` and `explorer`.
You said nerdtree is a `browser`? But actually, Nerdtree is, (and I quote from its repo README) "The NERDTree is a file system **explorer** for the Vim editor."

I'm getting confused... to most people (including me) a file-browser and file-explorer are both the same thing, so I would suggest choosing a different term to explain what you mean.

Are you thinking of `file-manager `maybe? Are you referring to the difference between a file browser/explorer vs a file manager?

This project does a bit of file management too.

I'm having trouble understanding where this project is going. So, in the meantime, I will pause my contributions... at least for now.

I would recommend you to clarify in the README what do you mean by this plugin being a `browser` and not an `explorer`.

I use `nerdtree` and I think it excels at both, project browsing (or exploring) and also file-management, but I do see that this plugin has a good potential in regards to search, that is why I got excited about it.

But it seems to me, that the goal of this project is not well defined yet, or maybe its just not communicated effectively. Either way, there are solutions :)

I'll keep an eye on this project. Good luck!

**Comment by fdschmidt93** [comment] 2022-01-04 22:00
These terms were merely exemplary defined to have short hands for illustration, nothing to dwell on.

I don't follow your fixation on this to such degree (talking about project "vision", "goals"). I accept your workflow, you don't seem to accept mine to the degree that you keep pushing for making yours the default. Both have pro's and con's in different scenarios.

In any case, I plan on incorporating your workflow/PR with proper documentation/discussion a configurable option, eventually. I'm at odds why this is not a sufficient compromise.

Ok thanks.

**Comment by miguelmoraperea** [comment] 2022-01-05 03:07
I don't have anything against your personal workflow. I just feel that is very particular to the way 'you' work/navigate on a project, and I'm not convinced that is the way most users work. Considering my PR doesn't change your workflow at all, have in mind that PR #40 will get merged.

Having said that, you are free to design this plugin as you prefer, you are the maintainer ultimately, I'm just a contributor.

But from my side, I also need to be careful that I don't spend my time/resources on a project that I don't fully understand its direction. I hope you understand and respect that.

Before I spend time making this feature an opt-in, I need to convince myself that is worth doing it. If I see this project is going in a different direction, then there is no point in me working on it. Does that make sense?

I don't feel you have been open to hearing my point of view, I know you accepted it as an opt-in, but you seem to stick to your own workflow as the one-and-only. Communication hasn't been clear either, which worries me a little.

Anyways, I believe PR #40 has the potential to change how users will use the plugin by adding a way to go-to-HOME and change the `cwd`.  Maybe that PR or other PRs might eventually change your workflow.

For now, I will wait until PR #40 is merged, then I will revisit my workflow, and will happily consider other workflows that could improve my efficiency.

I will try to compare the way I use `nerdtree` vs how I would use `telescope-file-browser`.  If I still see a potential on this plugin, and perhaps by then you have considered other workflows too, not just as opt-in but really consider them as the default too (I'm not saying you have to change it, but just consider them), then I'm happy to continue the work on this PR.

Like I said before, if you want to chat, brainstorm ideas, share workflows, etc in a constructive way, I'm willing to spend the time to do that. If not, that is ok too. :) no hard feelings.

**Closed** 2022-01-11 23:09 UTC
Labels: bug
