### ISSUE TITLE
'hijack_netrw = true' still calls netrw when you use the `:Explore` command

### ISSUE THREAD

**Issue by jam1015** [nvim-telescope/telescope-file-browser.nvim#204] opened 2022-12-23 20:25 UTC
### Description

the `hijack_netrw` setting hijack netrw works, but the expected behavior for me would be to block the calling of netrw completely.  right now this picker comes up over netrw, and when you escape out, you are left in netrw, not the buffer you called `:Explore` from

### Neovim version

```markdown
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux, Kernel: 6.0.10-arch2-1

### Steps to reproduce

1: Run `:Explore`
2: see that netrw is called

### Expected behavior

the telescope-file-browser picker should come up, without netrw being called

### Actual behavior

both netrw and the telescope-file-browser picker are called

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup({extensions = {file_browser = {hijack_netrw = true}}})
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment] 2022-12-23 21:11
I believe the docs are clear that `hijack_netrw`: "use telescope file browser when
opening directory paths; must beset on `setup` (default: false)". Hence `:Explore` _should_ open netrw.

I'm somewhat opposed to overriding `:Explore` by default as other users might have different expectations and it is easy to change on your end, but much much more tedious to opt out. We'd have to have yet another flag for that and I prefer to reduce the number of option flags.

`:Telescope file_browser path=%:p:h` would be the canonical way to achieve the netrw equivalent with `telescope-file-browser.nvim`.

You can then do

```lua
vim.api.nvim_create_user_command("Explore", "Telescope file_browser path=%:p:h", {})
``` 

to overwrite `Explore` on your end.

Closing for the time being _unless_ there is a really good case why this should be a builtin default/option.

**Closed by fdschmidt93** 2022-12-23 21:11 UTC
Labels: bug

**Comment by jamestrew** [comment] 2022-12-23 21:12
Any particular reason you're calling `:Explore` if you don't want to use the netrw explorer?

I'm a little hesitant touching netrw any more than necessary as it's been the cause of some headaches.
If you really would like to call `:Explore` and you do something like `vim.api.nvim_create_user_command("Explore", "Telescope file_browser", {})`

**Comment by jam1015** [comment] 2022-12-23 21:23
ok I understand everything now: should have read the docs.  I assert that if everything you've just said is true, then `:Explore` should call either netrw or this picker, not both at the same time as it currently does.

**Comment by fdschmidt93** [comment] 2022-12-23 21:33
That indeed shouldn't have happened. I just pushed a fix that suppresses `telescope-file-browser.nvim` if the `augroup` would be triggered from within a `netrw` buffer.
