### ISSUE TITLE
Create File With C-e launchs a prompt to insert file name.

### ISSUE THREAD

**Issue by stonecharioteer** [nvim-telescope/telescope-file-browser.nvim#50] opened 2022-01-10 06:08 UTC
### Description

I've just switched to this plugin from using Telescope's file browser because of the deprecation warning. I've encountered a strange behaviour though, which wasn't on Telescope itself.

When I type in the path of a file I want to create and hit C-e, I get a prompt in the command bar asking me to insert a file name.

![2022-01-10-113304_883x283_scrot](https://user-images.githubusercontent.com/11478411/148724343-b231f204-1d11-4c7a-a158-3dee52bab1b1.png)

### Neovim version

```markdown
NVIM v0.7.0-dev+839-g09d270bce
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az121-138

Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Ubuntu 21.10 Impish

### Steps to reproduce

Open the file browser, type the name of a file that doesn't exist (doesn't matter if in a new folder or in current folder), hit C-e, and you'll get the prompt.

### Expected behavior

This used to create the file and open it for editing in Telescope.

### Actual behavior

Opens prompt at the nvim command bar, asking to insert file path.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment] 2022-01-10 08:16
This is not a bug but a feature. `telescope-file-browser.nvim` levers `vim.ui.input` rather than parsing the line of the prompt buffer as that typically leads to hiding all results (due to changed prompt) which are contextual information possibly relevant to creating the file.

Closing for the time being as I think this sufficiently responds to the issue. Let me know in case there's more issues and we possibly reopen this one then.

**Closed by fdschmidt93** 2022-01-10 08:16 UTC
Labels: bug

**Comment by stonecharioteer** [comment] 2022-01-10 12:24
Ah so the flow is now just hit CTRL-e and then type the name of the file or relative path of the file? I used to do that within the file browser interface previously.

**Comment by fdschmidt93** [comment] 2022-01-10 13:13
The name of the file corresponding to the absolute path, meaning you could also create files in other directories, the default file path just defaults to the current working directory for convenience.

If the filename ends with `/` a folder is created.

Just create files and see what happens ;) with `telescope-file-browser.nvim` you can remove them just as fast.
