### ISSUE TITLE
which-key shortcut doesn't work

### ISSUE THREAD

**Issue by DavidePatria** [nvim-telescope/telescope-file-browser.nvim#59] opened 2022-01-12 10:00 UTC
### Description

I've recently discovered about a which-key shortcut for telescope pickers mentioned in telescope main repo
```
 mappings = {
      i = {
        -- map actions.which_key to <C-h> (default: <C-/>)
        -- actions.which_key shows the mappings for your picker,
        -- e.g. git_{create, delete, ...}_branch for the git_branches picker
        ["<C-h>"] = "which_key"
```

which doesn't work on the file browser

### Neovim version

```markdown
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

ubuntu 20.04

### Steps to reproduce

1. set a shortcut in telescope config file for the which-key functionality
2. use it flawlessly in other pickers.
3. try to use it in telescope file browser
4. wonder why it doesn't work

### Expected behavior

a window with the shortcut should appear as in other pickers.

### Actual behavior

nothing shows up

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment] 2022-01-12 10:14
```lua
require "telescope".setup {
  extensions = {
    file_browser = {
      mappings = {
        i = {
          ["<C-h>"] = "which_key",
        },
      }
    },
  },
}
```
works for me as intended (also on the 0.6.1 appimage). Could you please post your full telescope configuration?

**Comment by DavidePatria** [comment] 2022-01-12 10:23
I didn't get that mappings specified in `defaults` don't apply to extensions too, after adding the `file_browser` section it works
```
require('telescope').setup{

	extensions = {
		fzf = {
			fuzzy = true,                    -- false will only do exact matching
			override_generic_sorter = true,  -- override the generic sorter
			override_file_sorter = true,     -- override the file sorter
			case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
											 -- the default case_mode is "smart_case"
		},

		file_browser = {
			mappings = {
				i = { ["<c-h>"] = "which_key" },
			}
		}
	},

	defaults = {
    -- shortcut to send results to trouble
		mappings = {
			-- i = { ["<c-t>"] = trouble.open_with_trouble },
			i = { ["<c-h>"] = "which_key" },
			n = { ["<c-t>"] = trouble.open_with_trouble },
		},
```

but apparently the default layout applies also to the extension without specifying it again, strange.
Thank you

**Comment by fdschmidt93** [comment] 2022-01-12 10:30
> I didn't get that mappings specified in defaults don't apply to extensions too, after adding the file_browser section it works

I think that's a bug. I'll reopen this and try to look into it tonight.

**Comment by DavidePatria** [comment] 2022-01-12 10:31
fine. thanks again

**Comment by DavidePatria** [comment] 2022-01-12 11:08
another note: setting `<C-h>` as the shortcut for which-key removes the one to toggle hidden files, so another shortcut would be needed anyway. Still, setting it in defaults and have it telescope-wide would be useful.

**Comment by fdschmidt93** [comment] 2022-01-12 12:23
Seems like it was a straightforward fix, `telescope.default.mappings` should hopefully now be properly respected.

Closing until I get feedback otherwise.

Once again, thanks for reporting!

**Closed by fdschmidt93** 2022-01-12 12:23 UTC
Labels: bug
