### ISSUE TITLE
Renaming file just changing camel dont change thef ile

### ISSUE THREAD

**Issue by otavioschwanck** [nvim-telescope/telescope-file-browser.nvim#135] opened 2022-05-16 13:16 UTC
### Description

try to rename show.tsx to Show.tsx does't work

### Neovim version

```markdown
0.7
```

### Operating system and version

mac

### Steps to reproduce

try to rename show.tsx to Show.tsx 

### Expected behavior

file name change to Show.tsx

### Actual behavior

file continues show.tsx

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment] 2022-05-16 13:34
Cannot reproduce with neovim `master` and `stable` using the minimal init lua provided on Arch Linux.

Video shows neovim `stable` with latest `telescope-file-browser`

https://user-images.githubusercontent.com/39233597/168604674-5f34dd80-7947-4574-9894-23db7fac2d56.mp4

**Comment by fdschmidt93** [comment] 2022-05-16 13:48
Thanks for the feedback! So, I unfortunately cannot do anything here really as I don't own a Mac device. Can this "bug" even be fixed from within `telescope-file-browser.nvim` or `plenary.nvim`?

**Comment by otavioschwanck** [comment] 2022-05-16 16:50
> Once more, help from a Mac user would be very much appreciated here :)

what can i do to help?

**Comment by fdschmidt93** [comment] 2022-05-16 16:54
Relevant code is here

https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/7861dddeb3102880965bb3720250dd5c3cc5da33/lua/telescope/_extensions/file_browser/actions.lua#L235-L279

I guess
```lua
      old_path:rename { new_name = new_path.filename }
```

fails because `plenary.path` (check plenary repo) fails to distinguish between the files on MacOS.

**Comment by miversen33** [comment] 2022-05-22 18:17
Looking into plenary a bit, the relevant section for rename is found [here](https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/path.lua#L509-L533) and really doesn't do too much, delegating the rename to the libuv function [fs_rename](https://github.com/luvit/luv/blob/master/docs.md#uvfs_renamepath-new_path-callback)

@otavioschwanck 
What happens if you try to do your rename directly with libuv?
```
:lua vim.loop.fs_rename('show.tsx', Show.tsx')
```
Does that successfully do the requested rename?

**Comment by gegoune** [comment] 2022-05-22 18:25
Interesting, using `fs_rename()` worked for me on Mac.

**Comment by fdschmidt93** [comment] 2022-05-22 18:31
Do you get the notification that the file exists if you use `telescope-file-browser`?

**Comment by miversen33** [comment] 2022-05-22 18:36
> Interesting, using `fs_rename()` worked for me on Mac.

Interesting. @gegoune  as it sounds like you are able to verify for us, can you test a rename via `plenary`?
```
:lua require("plenary").path:new('show.tsx'):rename({new_name="Show.tsx"})
```

Does _this_ work?
The path we are following is
- does libuv work (sounds like this has been verified)
- does plenary work (verifying now)
- does telescope-file-browser work (verifying next)

**Comment by gegoune** [comment] 2022-05-22 19:08
Plenary does not seem to be creating that file at all for me. Tried limiting it to `:lua require("plenary").path:new('show.tsx')` but no new file shows up on filesystem in cwd.

**Comment by fdschmidt93** [comment] 2022-05-22 19:10
`Path:new(...)` doesn't create a new file, but just a `Path` object. This should be creating the file via `plenary`.

`:lua require("plenary").path:new('show.tsx'):touch()`

**Comment by gegoune** [comment] 2022-05-22 19:19
Here we go. Renaming does not work:
```
Vim(luafile):E5113: Error while calling lua chunk: ...site/pack/packer/start/plenary.nvim/lua/plenary/path.lua:526: File or dir
ectory already exists!
```
`show.tsx` got created now but not renamed. Which is expected as per Mac OS:
```shell
$ mv show.tsx Show.tsx
mv: 'show.tsx' and 'Show.tsx' are the same file
```

**Comment by fdschmidt93** [comment] 2022-05-22 19:38
If `plenary` behaves like `mv` on macOS, I'm inclined to say the original issue is expected behavior. Thoughts?

**Comment by miversen33** [comment] 2022-05-22 19:41
> If plenary behaves like mv on macOS, I'm inclined to say the original issue is expected behaviour. Thoughts?

I'd agree, though even if not, this clarifies that this should be an issue with Plenary and not telescope-file-browser. So whether this is an issue or not, probably should be migrated to the appropriate code base :)

That said, `mv` will also complain and a rename is just a move, I believe this is expected behavior. This would be the same as if you were to try and rename a file to itself (as that is what MacOS sees this command as), which will also fail.

Maybe worth bubbling the received plenary error up to the user though?

**Comment by fdschmidt93** [comment] 2022-05-22 19:54
> Maybe worth bubbling the received plenary error up to the user though?

I'm reasonably sure the user sees that error and OP is incomplete. @gegoune could you please confirm? :)

> this should be an issue with Plenary and not telescope-file-browser

Plenary path could use some love; it's quite underutilized. In practice, I've ended up making the relevant PRs and, practically speaking, it is unlikely anyone else would step up 😅

**Comment by gegoune** [comment] 2022-05-22 23:16
Well, replication you came up with @fdschmidt93 errors with traceback:
```
E5113: Error while calling lua chunk: ...site/pack/packer/start/plenary.nvim/lua/plenary/path.lua:526: File or directory already exists!
stack traceback:
        [C]: in function 'error'
        ...site/pack/packer/start/plenary.nvim/lua/plenary/path.lua:526: in function 'rename'
        test.lua:4: in main chunk
```

telescope-file-browser errors with: `[file_browser.action.rename] Show.tsx already exists! Skipping.` through `vim.notify()`

It's clear enough for those who know that APFS is case insensitive.

**Comment by otavioschwanck** [comment] 2022-05-23 00:56
> lua require("plenary").path:new('show.tsx'):rename({new_name="Show.tsx"})

Doesn't works, even chaging Show.tsx for something else

**Comment by otavioschwanck** [comment] 2022-05-23 00:58
> > Interesting, using `fs_rename()` worked for me on Mac.
> 
> Interesting. @gegoune as it sounds like you are able to verify for us, can you test a rename via `plenary`?
> 
> ```
> :lua require("plenary").path:new('show.tsx'):rename({new_name="Show.tsx"})
> ```
> 
> Does _this_ work? The path we are following is
> 
> * does libuv work (sounds like this has been verified)
> * does plenary work (verifying now)
> * does telescope-file-browser work (verifying next)

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/9551316/169724648-182135d0-29aa-4bd9-866e-e842326f4a5b.png">

**Comment by miversen33** [comment] 2022-05-23 01:08
Sounds like this is working as intended/expected then. Technically Plenary (a different repo altogether) could put a workaround to allow for renaming a file to itself but that shouldn't be considered IMO.

While I understand that you aren't _actually_ renaming the file to the same name (`show.tsx` != `Show.tsx`), MacOS believes these are the same and thus this error is both appropriate and expected.

This seems like a non-issue, especially as the error _does_ bubble up to the user.

**Comment by miversen33** [comment] 2022-05-23 02:06
@fdschmidt93 thoughts?
IMO this is a non-issue. The command you tried to do failed at an OS level as well (as shown by the attempt to `mv` the file in the same manner on the filesystem). The fact that vim and libuv are able to do this is a side effect and IMO not something that should be replicated in other file system interfaces as it strays away from what the actual Filesystem is doing underneath. As far as MacOS is concerned `show.tsx` and `Show.tsx` are the same file so a rename is nonsensical.

All of that said, I dont think a workaround would be super difficult to put in place, should the Plenary team chose to do so (I do not currently contribute to plenary (yet)).

**Comment by fdschmidt93** [comment] 2022-05-23 07:22
Yes, I fully agree. This can be closed here. Feel free to open an issue on `plenary`-side, but please don't have too much hope someone else "fixes" this for you.

Some general comments. In particular an (non-)issue like this one I recommend is best fixed by users facing and caring about the issue. After all, this is what makes open source go round. I'm happy to help, though in the long run, it is to some degree unsustainable for maintainers to serve all the issues in the project (I guess people here are aware I'm very active on `telescope.nvim` too). That's also why I indicated I'm not so interested in trying to "fix" this. Furthermore, OP provided incomplete information and was extremely tight-lipped on sufficient communication (took a while to certify that plenary raises a descriptive error, by another user), which isn't helping in getting something done about this (at least by me); in other words, I should have had closed the issue as `wontfix` already.

**Closed by fdschmidt93** 2022-05-23 07:22 UTC
Labels: bug, needs repro
