### ISSUE TITLE
requiring actions causes setup not to work

### ISSUE THREAD

**Issue by zdcthomas** [nvim-telescope/telescope-file-browser.nvim#28] opened 2021-12-17 04:58 UTC
### Description

First off, thank you everyone that's ever worked on any telescope related project, it's so cool and I use it everyday.

I've been trying to setup file_browser to be my main file browsing plugin, however:
With the config 
```lua
	local fb_actions = require("telescope").extensions.file_browser.actions
	require("telescope").setup({
		extensions = {
			file_browser = {
				theme = "ivy",
				mappings = {
					n = {
						["B"] = function()
							print("test")
						end,
					},
				},
			},
		},
	})
	require("telescope").load_extension("file_browser")
	vim.api.nvim_set_keymap(
		"n",
		"<Leader>n",
		"<cmd>lua require 'telescope'.extensions.file_browser.file_browser()<CR>",
		{ noremap = true, silent = true }
	)
```
neither the theme or any of the mappings appear when I either use the mapping `<Leader>n` or call `lua require 'telescope'.extensions.file_browser.file_browser()`

However, when I remove the actions require and change it to something like 
```lua
	require("telescope").setup({
		extensions = {
			file_browser = {
				theme = "ivy",
				mappings = {
					n = {
						["B"] = function()
							print("test")
						end,
					},
				},
			},
		},
	})
	require("telescope").load_extension("file_browser")
	vim.api.nvim_set_keymap(
		"n",
		"<Leader>n",
		"<cmd>lua require 'telescope'.extensions.file_browser.file_browser()<CR>",
		{ noremap = true, silent = true }
	)
```
Both he theme and the mappings work perfectly. 

I therefore believe it's due to the actions require at the top. 
I'll look into it more in the code but thought I'd make an issue first to track it.

### Neovim version

```markdown
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.0.1

### Steps to reproduce

1. nvim -nu minimal.lua
2. <Leader>n
3. <esc> (to enter normal mode)
4. B (should print out "test")

### Expected behavior

When I open the file browser, it will have the theme I specified and the mappings which I specify.

### Actual behavior

Actually doesn't have the config I specify or the mappings.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"nvim-telescope/telescope.nvim",
				requires = {
					"nvim-lua/plenary.nvim",
					"nvim-telescope/telescope-file-browser.nvim",
				},
			},
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
_G.load_config = function()
	local fb_actions = require("telescope").extensions.file_browser.actions
	require("telescope").setup({
		extensions = {
			file_browser = {
				theme = "ivy",
				mappings = {
					n = {
						["B"] = function()
							print("test")
						end,
					},
				},
			},
		},
	})
	require("telescope").load_extension("file_browser")
	vim.api.nvim_set_keymap(
		"n",
		"<Leader>n",
		"<cmd>lua require 'telescope'.extensions.file_browser.file_browser()<CR>",
		{ noremap = true, silent = true }
	)
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing Telescope and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Comment by fdschmidt93** [comment] 2021-12-17 07:07
Yes, that's a known issue and will have to be fixed upstream: https://github.com/nvim-telescope/telescope.nvim/pull/1601

For the time being, https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/6#issuecomment-974717683 shows a workaround by lazily requiring fb actions.

**Comment by zdcthomas** [comment] 2021-12-17 07:34
Right on, super sorry for not digging throughly enough! I assume you'd prefer I close this issue out?

**Comment by fdschmidt93** [comment] 2021-12-17 09:55
Let's leave this open until the issue is fixed upstream so any user running into the issue hopefully arrives here.

**Comment by fdschmidt93** [comment] 2021-12-27 16:56
The relevant upstream PR now has been merged and have resolved this issue. Please let me know in case there's more to do here.

**Closed by fdschmidt93** 2021-12-27 16:56 UTC
Labels: bug
